include classpath("application.conf")

node-address {
  port = 9324
}

rest-sqs {
  bind-port = 9324
}

messages-storage {
  enabled = false
}

auto-create-queues {
  enabled = true
  template {
    defaultVisibilityTimeout = 30 seconds
    tags {
        type = "dynamic"
    }
  }
}

queues {
  test { }

  01-simple-queue { }

  02-queue-with-dead-letter {
    defaultVisibilityTimeout = 10 seconds
    delay = 5 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "03-dead-letter-queue"
      maxReceiveCount = 3
    }
  }

  03-dead-letter-queue { }

  04-fifo-queue {
    fifo = true
    contentBasedDeduplication = true
  }
}
