[Global]
Ingester-UUID=b9757493-c5cf-4eb7-86d1-14ad95589066
Ingest-Secret=IngestSecrets
Connection-Timeout=10s
Insecure-Skip-TLS-Verify = false
Cleartext-Backend-Target=localhost:4023
Log-Level=INFO
Log-File=/tmp/kinesis.log
State-Store-Location=/tmp/kinesis_ingest.state

AWS-Access-Key-ID=kinesis_local
AWS-Secret-Access-Key=kinesis_local

[KinesisStream "testStream"]
  Endpoint=http://localhost:4567
	Region=us-east-1
	Tag-Name=kinesis
	Stream-Name=test
	Iterator-Type=TRIM_HORIZON
	Parse-Time=false
