[Global]
Ingester-UUID=4c9143f8-be73-4c4a-8fcc-ed05d8ce8fd0
Ingest-Secret=IngestSecrets
Cleartext-Backend-Target=localhost:4023
Log-File=/tmp/s3.log
State-Store-Location=/tmp/s3.state
Worker-Pool-Size=10
Connection-Timeout=10s

[Bucket "test"]
  Endpoint=http://localhost:3900
	Region=garage
	ID=garage_access_key
	Secret=garage_secret_key
	Bucket-Name=garage-bucket
	Tag-Name=s3
	Credentials-Type=static
	S3-Force-Path-Style=true
