[Global]
Ingester-UUID=4ea33733-19dd-4a21-92ed-172aceb0f9a5
Ingest-Secret=IngestSecrets
Cleartext-Backend-Target=localhost:4023
Log-File=/tmp/sqs.log

[Queue "test"]
	Region=us-east-1
	Endpoint=http://localhost:9324
	Queue-URL=http://localhost:9324/000000000000/test
	Tag-Name=sqs
	AKID=elasticmq
	Secret=elasticmq
	Credentials-Type=static
