/*************************************************************************
 * Copyright 2018 Gravwell, Inc. All rights reserved.
 * Contact: <legal@gravwell.io>
 *
 * This software may be modified and distributed under the terms of the
 * BSD 2-clause license. See the LICENSE file for details.
 **************************************************************************/

package main

var (
	subreddits []string = []string{`all`}
	/*
		subreddits []string = []string{
			//defaults
			`announcements`,
			`Art`,
			`AskReddit`,
			`askscience`,
			`aww`,
			`blog`,
			`books`,
			`creepy`,
			`dataisbeautiful`,
			`DIY`,
			`Documentaries`,
			`EarthPorn`,
			`explainlikeimfive`,
			`food`,
			`funny`,
			`Futurology`,
			`gadgets`,
			`gaming`,
			`GetMotivated`,
			`gifs`,
			`history`,
			`IAmA`,
			`InternetIsBeautiful`,
			`Jokes`,
			`LifeProTips`,
			`listentothis`,
			`mildlyinteresting`,
			`movies`,
			`Music`,
			`news`,
			`nosleep`,
			`nottheonion`,
			`OldSchoolCool`,
			`personalfinance`,
			`philosophy`,
			`photoshopbattles`,
			`pics`,
			`science`,
			`Showerthoughts`,
			`space`,
			`sports`,
			`television`,
			`tifu`,
			`todayilearned`,
			`TwoXChromosomes`,
			`UpliftingNews`,
			`videos`,
			`worldnews`,
			`WritingPrompts`,

			//some potentially interesting others added by hand
			`The_Donald`,
			`politics`,
			`russia`,
			`usa`,
			`wow`,
			`dnd`,
			`dndnext`,
			`leagueoflegends`,
			`fitness`,
			`bestof`,
			`Overwatch`,
			`pubg`,

			//some IT related subreddits
			`andSec`,
			`antiforensics`,
			`AskNetsec`,
			`aws`,
			`cableporn`,
			`ccna`,
			`Cisco`,
			`commandline`,
			`computerforensics`,
			`Database`,
			`Dell`,
			`devops`,
			`docker`,
			`Dockerfiles`,
			`homelab`,
			`HyperV`,
			`ipv6`,
			`ITManagers`,
			`Juniper`,
			`linux`,
			`linux4noobs`,
			`linuxadmin`,
			`linuxmint`,
			`lockpicking`,
			`mac`,
			`macserver`,
			`macsysadmin`,
			`microsoft`,
			`msp`,
			`nagios`,
			`netsec`,
			`netsecstudents`,
			`NetworkForSale`,
			`networking`,
			`openstack`,
			`osx`,
			`PFSENSE`,
			`PowerShell`,
			`pwned`,
			`SCCM`,
			`selinux`,
			`ServerPorn`,
			`sharepoint`,
			`shredporn`,
			`SocialEngineering`,
			`SQLServer`,
			`sysadmin`,
			`sysadminmeetups`,
			`sysadmintools`,
			`talesfromsysadmin`,
			`techforsale`,
			`usefulscripts`,
			`vmware`,
			`WindowsServer`,
		}
	*/
)
