[Global]
	#Ingester-UUID="90000000-0000-0000-0000-000000000000" #example UUID, remember to set
	Ingest-Secret = "IngestSecrets"
	Connection-Timeout = 0
	Insecure-Skip-TLS-Verify=false
	
	#Cleartext-Backend-Target=127.0.0.1:4023 #example of adding a cleartext connection
	#Cleartext-Backend-Target=127.1.0.1:4023 #example of adding another cleartext connection
	#Encrypted-Backend-Target=127.1.1.1:4024 #example of adding an encrypted connection
	#a named pipe connection, this should be used when ingester is on the same machine as a backend
	#Pipe-Backend-Target=/opt/gravwell/comms/pipe

	# always enable the cache for hosted ingesters
	Ingest-Cache-Path=/opt/gravwell/cache/hosted_runner.cache
	Max-Ingest-Cache=1024 #Number of MB to store, localcache will only store 1GB before stopping.  This is a safety net

	# log levels and output files
	Log-Level=INFO
	Log-File=/opt/gravwell/log/hosted_runner.log

# configure the state file for hosted ingesters
[State]
	Path="/opt/gravwell/etc/hosted_runner.state"
	Sync=false #do NOT flush to disk on every sync (sync=true mode can be expensive if disks are slow)

# [Okta "test"]
	#Ingester-UUID="92000000-0000-0000-0000-000000000000" #example UUID, remember to set
 	#Domain="example-org.okta.com" #okta organization domain
 	#Token="this-is-my-token-there-are-many-like-it-but-this-one-is-mine" # Okta API token
	#Request-Batch-Size=100 #optionally override batch size, default is 100, max is 3000
	#Request-Per-Minute=10 #optionally override RPM on API, default is 60, max is 6000
	#Request-Burst=20 #optionally override request burst (leaky bucket limited), default is 10

#[Mimecast "mimecast"]
	#Ingester-UUID="99000000-0000-0000-0000-000000000000" #example UUID, remember to set
	#Lookback=48 # in hours
	#Client-Id="id"
	#Client-Secret="secret"
	#Api=audit
	#Api=mta-delivery # all options can be found in ../plugins/mimecast/events.go (Api type)
	#Tag-Prefix="mimecast"
	#Request-Interval=5 # in seconds

