/*************************************************************************
 * Copyright 2024 Gravwell, Inc. All rights reserved.
 * Contact: <legal@gravwell.io>
 *
 * This software may be modified and distributed under the terms of the
 * BSD 2-clause license. See the LICENSE file for details.
 **************************************************************************/

package scaffoldcreate

import (
	"errors"
	"fmt"

	"github.com/charmbracelet/bubbles/textinput"
	"github.com/gravwell/gravwell/v4/gwcli/clilog"
	"github.com/gravwell/gravwell/v4/gwcli/stylesheet"
	ft "github.com/gravwell/gravwell/v4/gwcli/stylesheet/flagtext"
	"github.com/gravwell/gravwell/v4/gwcli/utilities/uniques"

	"github.com/spf13/pflag"
)

// FieldType (though currently not utilized) is intended as an expandable way to add new data inputs,
// such as checkboxes or radio buttons. It alters the draw in .View and how data is parsed from the
// Field's flag.
type FieldType = string

const (
	Text FieldType = "text" // string inputs, consumed via flag.String & textinput.Model
	File FieldType = "file" // takes a path as a string. In interactive mode, uses a pathtextinput.Model
	// TODO add boolean, add label
)
// FlagConfig defines settings for customizing how the flag for this field is displayed and handled.
type FlagConfig struct {
	Name      string // Longform flag (ex: --flagname). Defaults to DeriveFlagName() if unset.
	Usage     string // Description displayed with -h.
	Shorthand rune   // Shortform flag (ex: -f). Omitted if unset.
}

// A Field defines a single data point that will be passed to the create function.
type Field struct {
	Required     bool       // this field must be populated prior to calling createFunc
	Title        string     // field name displayed next to prompt and as flag name // TODO remove
	Type         FieldType  // type of field, dictating how it is presented to the user // TODO remove
	Flag         FlagConfig // OPTIONAL. Control how this field's flag is handled.
	DefaultValue string     // OPTIONAL. Default flag and TI value
	Order        int        // OPTIONAL. Top-Down (highest to lowest) display order of this field.

	Provider FieldProvider

	// OPTIONAL. USED ONLY FOR TEXT TYPE.
	// Called once, at program start to generate a TI instead of using a generalize newTI().
	// Can be used to add a ValidateFunc to the TI.
	CustomTIFuncInit func() textinput.Model
	// OPTIONAL. USED ONLY FOR TEXT TYPE.
	// Called every SetArg() (prior to passing control to the child create action), if not nil.
	// The associated TI will be replaced by the returned Model.
	CustomTIFuncSetArg func(*textinput.Model) textinput.Model
}

// Valid returns why the field is currently invalid (or nil), generally due to missing required fields.
func (f *Field) Valid() error {
	switch {
	case f.Title == "":
		return errors.New("title is required")
	case f.Type == "":
		return errors.New("type is required")
	}

	return nil
}

// Returns a FlagSet built from the given fields.
//
// Flags are generated by deriving a name (if field.FlagName is empty),
// then mapping field.Type to a native flag type (ex: StringP, Int).
func installFlagsFromFields(fields Config) pflag.FlagSet {
	var flags pflag.FlagSet
	for key, f := range fields {
		if f.Flag.Name == "" {
			f.Flag.Name = ft.DeriveFlagName(f.Title)
			fields[key] = f
		}

		// map fields to their flags
		switch f.Type {
		case Text, File:
			if f.Flag.Shorthand != 0 {
				flags.StringP(f.Flag.Name, string(f.Flag.Shorthand), f.DefaultValue, f.Flag.Usage)
			} else {
				flags.String(
					f.Flag.Name,
					f.DefaultValue, // default flag value
					f.Flag.Usage)
			}
		default:
			clilog.Writer.Error("failed to install flag for field next input: unknown field type",
				attachLogInfo(key, f.Type)...)
		}
	}

	return flags
}

// Given a parsed flagset and the field configuration, generates a map of values between fields and their current values
// (field -> fieldValue).
//
// Returns the values for each flag (default if unset),
// a list of required fields (as their flag names) that were not set,
// and an error (if one occurred).
//
// ! Does not test Files for existent paths; only that the strings are valid paths.
func getFieldValuesFromFlags(fs *pflag.FlagSet, fields Config) (fieldValues map[string]string, missingRequireds []string, err error) {
	fieldValues = make(map[string]string)
	for key, f := range fields {
		if f.Flag.Name == "" {
			return nil, nil, fmt.Errorf("field %s has an empty flag name", key)
		}
		// if this value is required, but unset, add it to the list and move on.
		// NOTE(rlandau): this uses fs.Changed(), which will fail default values.
		// I am assuming that if you need a value, a default is irrelevant.
		if f.Required && !fs.Changed(f.Flag.Name) {
			missingRequireds = append(missingRequireds, f.Flag.Name)
			continue
		}

		switch f.Type {
		case File:
			v, err := fs.GetString(f.Flag.Name)
			if err != nil {
				return nil, nil, err
			}
			fieldValues[key] = v
		case Text:
			v, err := fs.GetString(f.Flag.Name)
			if err != nil {
				return nil, nil, err
			}
			fieldValues[key] = v
		default:
			clilog.Writer.Error("failed to get value for field from flag: unknown field type",
				attachLogInfo(key, f.Type)...)
		}
	}
	return fieldValues, missingRequireds, nil
}

// FieldName returns a struct suited for Name inputs.
// Order == 100.
func FieldName(singular string) Field {
	return Field{
		Required: true,
		Flag: FlagConfig{
			Name:      ft.Name.Name(),
			Usage:     ft.Name.Usage(singular),
			Shorthand: rune(ft.Name.Shorthand()[0]),
		},
		Type:     Text,
		Order:    100,
		Provider: &TextProvider{Title: ft.Name.Name()},
	}
}

// FieldDescription returns a struct suited for Description inputs.
// Order == 90.
func FieldDescription(singular string) Field {
	return Field{
		Required: false,
		Flag: FlagConfig{
			Name:      ft.Description.Name(),
			Usage:     ft.Description.Usage(singular),
			Shorthand: rune(ft.Description.Shorthand()[0]),
		},
		Type:     Text,
		Order:    90,
		Provider: &TextProvider{Title: ft.Description.Name()},
	}
}

// FieldPath returns a struct suited for file path specification inputs.
// Order == 80.
func FieldPath(singular string) Field {
	return Field{
		Required: true,
		Flag: FlagConfig{
			Name:      ft.Path.Name(),
			Usage:     ft.Path.Usage(singular),
			Shorthand: rune(ft.Path.Shorthand()[0]),
		},
		Type:     File,
		Order:    80,
		Provider: &TextProvider{Title: ft.Path.Name()},
	}
}

// FieldLabels returns a struct suited for taking in labels as "<1>,<2>,<3>".
// Order == 70.
func FieldLabels() Field {
	return Field{
		Required: false,
		Flag: FlagConfig{
			Name:  "labels",
			Usage: "comma-separated list of labels to apply",
		},
		Type:  Text,
		Order: 70,
		Provider: &TextProvider{
			Title: "Labels",
			CustomInit: func() textinput.Model {
			ti := stylesheet.NewTI("", true)
			ti.Placeholder = "label1,label2,label3,..."
			return ti
			},
		},
	}
}

// FieldFrequency returns a struct suitable for taking in the frequency of something occurring as a cron string.
// Attaches uniques.CronRuneValidator and shorthand -c.
// Order == 50.
func FieldFrequency() Field {
	return Field{
		Required: true,
		Flag: FlagConfig{
			Name:      ft.Frequency.Name(),
			Usage:     ft.Frequency.Usage(),
			Shorthand: rune(ft.Frequency.Shorthand()[0]),
		},

		Type: Text,

		Order: 50,
		Provider: &TextProvider{
			Title: "Frequency",
			CustomInit: func() textinput.Model {
			ti := stylesheet.NewTI("", false)
			ti.Placeholder = "* * * * *"
			ti.Validate = uniques.CronRuneValidator
			return ti
			},
		},
	}
}
