/*************************************************************************
 * Copyright 2024 Gravwell, Inc. All rights reserved.
 * Contact: <legal@gravwell.io>
 *
 * This software may be modified and distributed under the terms of the
 * BSD 2-clause license. See the LICENSE file for details.
 **************************************************************************/

package scaffoldcreate

import (
	"errors"
	"fmt"

	"github.com/charmbracelet/bubbles/textinput"
	"github.com/gravwell/gravwell/v4/gwcli/clilog"
	"github.com/gravwell/gravwell/v4/gwcli/stylesheet"
	ft "github.com/gravwell/gravwell/v4/gwcli/stylesheet/flagtext"

	"github.com/spf13/pflag"
)

// FieldType (though currently not utilized) is intended as an expandable way to add new data inputs,
// such as checkboxes or radio buttons. It alters the draw in .View and how data is parsed from the
// Field's flag.
type FieldType = string

const (
	Text FieldType = "text" // string inputs, consumed via flag.String & textinput.Model
	File FieldType = "file" // takes a path as a string. In interactive mode, uses a pathtextinput.Model
	// TODO add boolean, add label
)

// A Field defines a single data point that will be passed to the create function.
type Field struct {
	Required      bool      // this field must be populated prior to calling createFunc
	Title         string    // field name displayed next to prompt and as flag name
	Usage         string    // OPTIONAL. Flag usage displayed via -h
	Type          FieldType // type of field, dictating how it is presented to the user
	FlagName      string    // OPTIONAL. Defaults to DeriveFlagName() result.
	FlagShorthand rune      // OPTIONAL. '-x' form of FlagName.
	DefaultValue  string    // OPTIONAL. Default flag and TI value
	Order         int       // OPTIONAL. Top-Down (highest to lowest) display order of this field.

	// OPTIONAL. USED ONLY FOR TEXT TYPE.
	// Called once, at program start to generate a TI instead of using a generalize newTI().
	// Can be used to add a ValidateFunc to the TI.
	CustomTIFuncInit func() textinput.Model
	// OPTIONAL. USED ONLY FOR TEXT TYPE.
	// Called every SetArg() (prior to passing control to the child create action), if not nil.
	// The associated TI will be replaced by the returned Model.
	CustomTIFuncSetArg func(*textinput.Model) textinput.Model
}

// Valid returns why the field is currently invalid (or nil), generally due to missing required fields.
func (f *Field) Valid() error {
	switch {
	case f.Title == "":
		return errors.New("title is required")
	case f.Type == "":
		return errors.New("type is required")
	}

	return nil
}

// Returns a FlagSet built from the given fields.
//
// Flags are generated by deriving a name (if field.FlagName is empty),
// then mapping field.Type to a native flag type (ex: StringP, Int).
func installFlagsFromFields(fields Config) pflag.FlagSet {
	var flags pflag.FlagSet
	for key, f := range fields {
		if f.FlagName == "" {
			f.FlagName = ft.DeriveFlagName(f.Title)
			fields[key] = f
		}

		// map fields to their flags
		switch f.Type {
		case Text, File:
			if f.FlagShorthand != 0 {
				flags.StringP(f.FlagName, string(f.FlagShorthand), f.DefaultValue, f.Usage)
			} else {
				flags.String(
					f.FlagName,
					f.DefaultValue, // default flag value
					f.Usage)
			}
		default:
			clilog.Writer.Error("failed to install flag for field next input: unknown field type",
				attachLogInfo(key, f.Type)...)
		}
	}

	return flags
}

// Given a parsed flagset and the field configuration, generates a map of values between fields and their current values
// (field -> fieldValue).
//
// Returns the values for each flag (default if unset),
// a list of required fields (as their flag names) that were not set,
// and an error (if one occurred).
//
// ! Does not test Files for existent paths; only that the strings are valid paths.
func getFieldValuesFromFlags(fs *pflag.FlagSet, fields Config) (fieldValues map[string]string, missingRequireds []string, err error) {
	fieldValues = make(map[string]string)
	for key, f := range fields {
		if f.FlagName == "" {
			return nil, nil, fmt.Errorf("field %s has an empty flag name", key)
		}
		// if this value is required, but unset, add it to the list and move on.
		// NOTE(rlandau): this uses fs.Changed(), which will fail default values.
		// I am assuming that if you need a value, a default is irrelevant.
		if f.Required && !fs.Changed(f.FlagName) {
			missingRequireds = append(missingRequireds, f.FlagName)
			continue
		}

		switch f.Type {
		case File:
			v, err := fs.GetString(f.FlagName)
			if err != nil {
				return nil, nil, err
			}
			fieldValues[key] = v
		case Text:
			v, err := fs.GetString(f.FlagName)
			if err != nil {
				return nil, nil, err
			}
			fieldValues[key] = v
		default:
			clilog.Writer.Error("failed to get value for field from flag: unknown field type",
				attachLogInfo(key, f.Type)...)
		}
	}
	return fieldValues, missingRequireds, nil
}

// FieldName returns a struct suited for Name inputs.
// Order == 100.
func FieldName(singular string) Field {
	return Field{
		Required:      true,
		Title:         "name",
		Usage:         ft.Name.Usage(singular),
		Type:          Text,
		FlagName:      ft.Name.Name(),
		FlagShorthand: rune(ft.Name.Shorthand()[0]),
		Order:         100,
	}
}

// FieldDescription returns a struct suited for Description inputs.
// Order == 90.
func FieldDescription(singular string) Field {
	return Field{
		Required:      false,
		Title:         "description",
		Usage:         ft.Description.Usage(singular),
		Type:          Text,
		FlagName:      ft.Description.Name(),
		FlagShorthand: rune(ft.Description.Shorthand()[0]),
		Order:         90,
	}
}

// FieldPath returns a struct suited for file path specification inputs.
// Order == 80.
func FieldPath(singular string) Field {
	return Field{
		Required:      true,
		Title:         ft.Path.Name(),
		Usage:         ft.Path.Usage(singular),
		Type:          File,
		FlagShorthand: rune(ft.Path.Shorthand()[0]),
		Order:         80,
	}
}

// FieldLabels returns a struct suited for taking in labels as "<1>,<2>,<3>".
// Order == 70.
func FieldLabels() Field {
	return Field{
		Required: false,
		Title:    "Labels",
		Usage:    "comma-separated list of labels to apply",
		Type:     Text,
		FlagName: "labels",
		Order:    70,
		CustomTIFuncInit: func() textinput.Model {
			ti := stylesheet.NewTI("", true)
			ti.Placeholder = "label1,label2,label3,..."
			return ti
		},
	}
}
