#!/bin/bash

set -e

# get things all staged up
go mod tidy
go mod download
go mod verify
go install golang.org/x/vuln/cmd/govulncheck@latest
go install honnef.co/go/tools/cmd/staticcheck@latest

echo "Running go vet"
	go vet ./generators/ipgen
        go vet ./chancacher
        go vet ./ingest
        go vet ./ingest/entry
        go vet ./ingest/processors
        go vet ./ingest/processors/plugin
        go vet ./ingest/config
        go vet ./ingest/log
        go vet ./timegrinder
        go vet ./filewatch
        go vet ./ingesters/utils
        go vet ./ingesters/kafka_consumer
        go vet ./ingesters/SimpleRelay
        go vet ./ipexist
        go vet ./netflow
        go vet ./client/...
        go vet ./gwcli/...


echo "Running go test -v"
	go test -v ./generators/ipgen
        go test -v ./chancacher
        go test -v ./ingest
        go test -v ./ingest/entry
        go test -v ./ingest/processors
        go test -v ./ingest/processors/plugin
        go test -v ./ingest/config
        go test -v ./ingest/log
        go test -v ./timegrinder
        go test -v ./filewatch
        go test -v ./ingesters/utils
        go test -v ./ingesters/kafka_consumer
        go test -v ./ingesters/SimpleRelay
        go test -v ./ipexist
        go test -v ./netflow
        go test -v ./client/...
        go test -v -tags ci ./gwcli/...

echo "running staticcheck"
	staticcheck ./gwcli/...
	staticcheck ./generators/base/... ./generators/gravwellGenerator/... ./generators/ipgen/...
	GOOS=windows staticcheck ./generators/windowsEventGenerator/...
	GOOS=windows staticcheck ./winevent/...
	GOOS=windows staticcheck ./ingesters/winevents/...
        staticcheck ./debug/...
        staticcheck ./manager/...
        staticcheck ./chancacher/...
	staticcheck ./ingest
	staticcheck ./ingest/attach
	staticcheck ./ingest/config/...
	staticcheck ./ingest/log/...
	staticcheck ./ingest/entry
	staticcheck ./ingest/processors
	staticcheck ./ingest/processors/plugin
	staticcheck ./ingest/processors/tags
	staticcheck ./utils/...
	staticcheck ./tools/...
	staticcheck ./timegrinder/...
	staticcheck ./ipexist/...
	staticcheck ./sqs_common/...
	staticcheck ./kitctl/...
	staticcheck ./netflow/...
	staticcheck ./migrate/...
	staticcheck ./filewatch/...
	staticcheck ./client/...
	staticcheck ./ingesters/args/...
	staticcheck ./ingesters/base/...
	staticcheck ./ingesters/utils/...
	staticcheck ./ingesters/AzureEventHubs/...
	staticcheck ./ingesters/canbus/...
	staticcheck ./ingesters/version/...
	staticcheck ./ingesters/collectd/...
	staticcheck ./ingesters/diskmonitor/...
	staticcheck ./ingesters/fileFollow/...
	staticcheck ./ingesters/GooglePubSubIngester/...
	staticcheck ./ingesters/hackernews_ingester/...
	staticcheck ./ingesters/IPMIIngester/...
	staticcheck ./ingesters/kafka_consumer/...
	staticcheck ./ingesters/KinesisIngester/...
	staticcheck ./ingesters/massFile/...
	staticcheck ./ingesters/MSGraphIngester/...
	staticcheck ./ingesters/multiFile/...
	staticcheck ./ingesters/netflow/...
	staticcheck ./ingesters/networkLog/...
	staticcheck ./ingesters/O365Ingester/...
	staticcheck ./ingesters/PacketFleet/...
	staticcheck ./ingesters/pcapFileIngester/...
	staticcheck ./ingesters/reddit_ingester/...
	staticcheck ./ingesters/regexFile/...
	staticcheck ./ingesters/reimport/...
	staticcheck ./ingesters/s3Ingester/...
	staticcheck ./ingesters/session/...
	staticcheck ./ingesters/Shodan/...
	staticcheck ./ingesters/SimpleRelay/...
	staticcheck ./ingesters/singleFile/...
	staticcheck ./ingesters/snmp/...
	staticcheck ./ingesters/sqsIngester/...
	staticcheck ./ingesters/xlsxIngester/...
	staticcheck ./ingesters/HttpIngester/...

echo "running govluncheck on everything"
        govulncheck -test ./netflow/...
        govulncheck -test ./manager/...
        govulncheck -test ./ipexist/...
        govulncheck -test ./generators/ipgen/...
        govulncheck -test ./generators/base/...
        govulncheck -test ./generators/gravwellGenerator/...
        govulncheck -test ./filewatch/...
        govulncheck -test ./client/...
        govulncheck -test ./chancacher/...
        govulncheck -test ./timegrinder/...
        govulncheck -test ./ingest
        govulncheck -test ./ingest/entry/...
        govulncheck -test ./ingest/config/...
        govulncheck -test ./ingest/log
        govulncheck -test ./ingest/processors
        govulncheck -test ./ingest/processors/tags
        govulncheck -test ./ingest/processors/plugin
        govulncheck -test ./tools/...
        govulncheck -test ./kitctl/...
        govulncheck -test ./migrate/...
        govulncheck -test ./ingesters/s3Ingester
        govulncheck -test ./ingesters/HttpIngester
        govulncheck -test ./ingesters/pcapFileIngester
        govulncheck -test ./ingesters/collectd
        govulncheck -test ./ingesters/hackernews_ingester
        govulncheck -test ./ingesters/base
        govulncheck -test ./ingesters/massFile
        govulncheck -test ./ingesters/MSGraphIngester
        govulncheck -test ./ingesters/kafka_consumer
        govulncheck -test ./ingesters/reddit_ingester
        govulncheck -test ./ingesters/O365Ingester
        govulncheck -test ./ingesters/args
        govulncheck -test ./ingesters/version
        govulncheck -test ./ingesters/sqsIngester
        govulncheck -test ./ingesters/diskmonitor
        govulncheck -test ./ingesters/session
        govulncheck -test ./ingesters/snmp
        govulncheck -test ./ingesters/xlsxIngester
        govulncheck -test ./ingesters/multiFile
        govulncheck -test ./ingesters/Shodan
        govulncheck -test ./ingesters/reimport
        govulncheck -test ./ingesters/SimpleRelay
        govulncheck -test ./ingesters/KinesisIngester
        govulncheck -test ./ingesters/netflow
        govulncheck -test ./ingesters/AzureEventHubs
        govulncheck -test ./ingesters/utils
        govulncheck -test ./ingesters/IPMIIngester
        govulncheck -test ./ingesters/regexFile
        govulncheck -test ./ingesters/PacketFleet
        govulncheck -test ./ingesters/canbus
        govulncheck -test ./ingesters/GooglePubSubIngester
        govulncheck -test ./ingesters/fileFollow
        govulncheck -test ./ingesters/singleFile
        #govulncheck -test ./gwcli
        GOOS=windows govulncheck -test ./ingesters/winevents
        GOOS=windows govulncheck -test ./winevent/...


echo "Running build tests"
        go build -o /dev/null ./generators/gravwellGenerator
        go build -o /dev/null ./manager
        go build -o /dev/null ./migrate
        go build -o /dev/null ./tools/timetester
        go build -o /dev/null ./timegrinder/cmd
        go build -o /dev/null ./ipexist/textinput
        go build -o /dev/null ./kitctl
        GOOS=windows go build -o /dev/null ./ingesters/fileFollow
        GOOS=windows go build -o /dev/null ./ingesters/winevents
        GOOS=windows go build ./generators/windowsEventGenerator
        go build -o /dev/null ./ingesters/massFile
        go build -o /dev/null ./ingesters/diskmonitor
        go build -o /dev/null ./ingesters/xlsxIngester
        go build -o /dev/null ./ingesters/reimport
        go build -o /dev/null ./ingesters/version
        go build -o /dev/null ./ingesters/canbus
        go build -o /dev/null ./ingesters/reddit_ingester
        go build -o /dev/null ./ingesters/hackernews_ingester
        go build -o /dev/null ./ingesters/multiFile
        go build -o /dev/null ./ingesters/session
        go build -o /dev/null ./ingesters/regexFile
        go build -o /dev/null ./ingesters/Shodan
        go build -o /dev/null ./ingesters/singleFile
        go build -o /dev/null ./ingesters/pcapFileIngester
        go build -o /dev/null ./gwcli
        GOOS=darwin GOARCH=amd64 go build -o /dev/null ./ingesters/fileFollow
        GOOS=darwin GOARCH=arm64 go build -o /dev/null ./ingesters/fileFollow
        GOOS=linux GOARCH=arm64 go build -o /dev/null ./ingesters/fileFollow
